name: mlflow_app
description: A Flutter application to view MLFlow experiments and metrics.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.2
  provider: ^6.1.1
  fl_chart: ^0.65.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_slidable: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  loading_animation_widget: ^1.2.0+4
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
